spring:
  application:
    name: spring-redis

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
    address: redis://127.0.0.1:6379


cache:
  type:
    local: guava
    distribute: redis

distribute:
  type:
    lock: redisson
    semaphore: redisson


redis:
  arrange:
    type: single # single or cluster